### ISSUE TITLE
Build fails: cannot use s (type memcache.Stats) as type map

### ISSUE THREAD

**Issue by nsams** [prometheus/memcached_exporter#10]
$ go get -v
    github.com/Snapbug/gomemcache (download)
    github.com/prometheus/client_golang (download)
    github.com/beorn7/perks (download)
    github.com/golang/protobuf (download)
    github.com/prometheus/client_model (download)
    github.com/prometheus/common (download)
    github.com/matttproud/golang_protobuf_extensions (download)
    github.com/prometheus/procfs (download)
    github.com/prometheus/log (download)
    github.com/Sirupsen/logrus (download)
    github.com/Snapbug/gomemcache/memcache
    github.com/beorn7/perks/quantile
    github.com/golang/protobuf/proto
    github.com/prometheus/common/internal/bitbucket.org/ww/goautoneg
    github.com/prometheus/common/model
    github.com/prometheus/procfs
    github.com/Sirupsen/logrus
    github.com/prometheus/log
    github.com/prometheus/client_model/go
    github.com/matttproud/golang_protobuf_extensions/pbutil
    github.com/prometheus/common/expfmt
    github.com/prometheus/client_golang/prometheus
    _/home/niko/memcached_exporter
    # _/home/niko/memcached_exporter
    ./main.go:171: cannot use s (type memcache.Stats) as type map[string]string in argument to parse
    ./main.go:172: invalid operation: s["version"] (type memcache.Stats does not support indexing)
    ./main.go:175: cannot use s (type memcache.Stats) as type map[string]string in argument to parse
    ./main.go:176: cannot use s (type memcache.Stats) as type map[string]string in argument to parse
    ./main.go:178: cannot use s (type memcache.Stats) as type map[string]string in argument to parse
    ./main.go:179: cannot use s (type memcache.Stats) as type map[string]string in argument to parse
    ./main.go:183: invalid operation: s["cmd_set"] (type memcache.Stats does not support indexing)
    ./main.go:184: cannot use s (type memcache.Stats) as type map[string]string in argument to sum
    ./main.go:190: invalid operation: s["cmd_set"] (type memcache.Stats does not support indexing)
    ./main.go:194: cannot use s (type memcache.Stats) as type map[string]string in argument to parse
    ./main.go:194: too many errors

**Comment by grobie** [comment]
All dependencies are vendored. Make sure to use a recent version of go.

**Comment by nsams** [comment]
Ok, sorry I'm new to go :/

Please help me with building, this is what I did:

    $ go version
    go version go1.7 linux/amd64
    $ env | grep GO
    GOBIN=/home/niko/go/bin
    GOPATH=/home/niko/go
    $ rm -rf /home/niko/go/*
    $ make
    >> formatting code
    can't load package: package _/home/niko/memcached_exporter: cannot find package "_/home/niko/memcached_exporter" in any of:
            /usr/lib/go/src/_/home/niko/memcached_exporter (from $GOROOT)
            /home/niko/go/src/_/home/niko/memcached_exporter (from $GOPATH)
    make: *** [Makefile:35: format] Error 1

**Comment by grobie** [comment]
@nsams Go has strict requirements how to structure your GOPATH. Make sure the project is checked out under `$GOPATH/src/github.com/prometheus/memcached_exporter`. This will happen automatically if you execute `go get github.com/prometheus/memcached_exporter`.

**Comment by nsams** [comment]
@grobie thanks!

that GOPATH is strange :/
