### ISSUE TITLE
what version of memcached this exporter support?

### ISSUE THREAD

**Issue by ariefMudahMy** [prometheus/memcached_exporter#103]
Hi,
currently im using memcached  version 1.2.2.
does this version of memcached supported?

when i run the exporter it show this logs
`level=info ts=2021-02-18T09:52:28.571Z caller=main.go:49 msg="Starting memcached_exporter" version="(version=0.8.0, branch=HEAD, revision=3d8ce192c21319731f1ac784af16a72468dcca5d)"
level=info ts=2021-02-18T09:52:28.571Z caller=main.go:50 msg="Build context" context="(go=go1.15.5, user=root@5ba0dc63dc36, date=20201204-19:29:03)"
level=info ts=2021-02-18T09:52:28.572Z caller=main.go:84 msg="Listening on address" address=:9150
level=error ts=2021-02-18T09:52:52.287Z caller=exporter.go:582 msg="Could not query stats settings" err="memcache: unexpected stats line format \"ERROR\\r\\n\""
level=error ts=2021-02-18T09:52:52.287Z caller=exporter.go:653 msg="Failed to parse cas" err="key not found"
level=error ts=2021-02-18T09:52:52.287Z caller=exporter.go:738 msg="Failed to parse set" err="key not found"
level=error ts=2021-02-18T09:52:52.287Z caller=exporter.go:738 msg="Failed to parse set" err="key not found"
level=error ts=2021-02-18T09:52:52.287Z caller=exporter.go:738 msg="Failed to parse set" err="key not found"
level=error ts=2021-02-18T09:52:52.288Z caller=exporter.go:738 msg="Failed to parse set" err="key not found"`

**Comment by SuperQ** [comment]
memcached 1.2.2 is from 2009. This is not supported. You should upgrade to at least 1.5.x or 1.6.x.
