### ISSUE TITLE
A server has multiple memcaches deployed, how can I start a memcached_exporter to monitor the service

### ISSUE THREAD

**Issue by zhxd163** [prometheus/memcached_exporter#111]
A server has multiple memcaches deployed, how can I start a memcached_exporter to monitor the service

./memcached_exporter --web.listen-address=":9111" --memcached.address=“xxxx:1111,XXXX:2222”

**Comment by zhxd163** [comment]
msg="Failed to connect to memcached" err="address XXXX:1111,XXXXX:2222,XXXXX:3333: too many colons in address"

**Comment by SpootDev** [comment]
I just created another service to do both memcache endpoints.  One exporter service for each memcache port.

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.

**Comment by DavidLeeUX** [comment]
> msg="Failed to connect to memcached" err="address XXXX:1111,XXXXX:2222,XXXXX:3333: too many colons in address"

https://github.com/DavidLeeUX/memcached_exporter

**Comment by SuperQ** [comment]
The way to support this is to add [multi-target param support](https://prometheus.io/docs/guides/multi-target-exporter/).

**Comment by SuperQ** [comment]
I am going to close this and create a new issue for multi-target spport.
