### ISSUE TITLE
Hi,I had a problem with memcached-exporter

### ISSUE THREAD

**Issue by dudumao520** [prometheus/memcached_exporter#115]
Hi,I tried memcached in version 1.4.25 and 1.6.9, but I couldn't monitor the data. I made sure that I followed the document specification,Ubuntu16.04LTS+[memcached1.4.25| memcached1.6.9]+memcached-exporter0.9.
In the IP address: 9150 port, i can see some data, but they are useless data
![01](https://user-images.githubusercontent.com/12032241/124374887-5c50b200-dcd1-11eb-9cb9-a982c9a2912f.png)
![02](https://user-images.githubusercontent.com/12032241/124374888-5d81df00-dcd1-11eb-8138-ebd3bd00a51f.png)
Please give me some good suggestions. Thank you very much！！！

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
