### ISSUE TITLE
extstore statistics

### ISSUE THREAD

**Issue by arodland** [prometheus/memcached_exporter#116]
When [extstore](https://github.com/memcached/memcached/wiki/Extstore) is enabled, `stats` outputs some additional stats relating to it. They're in line with existing stats (storage used/limit, read/write/eviction counts, etc.) and adding them to the exporter is pretty simple, but they don't exist when extstore isn't enabled, so it requires some special handling to only export them when they actually exist, which I'm not quite sure on how to do.

<details>
<summary>Example of stats</summary>

```
STAT extstore_compact_lost 0
STAT extstore_compact_rescues 0
STAT extstore_compact_skipped 0
STAT extstore_page_allocs 0
STAT extstore_page_evictions 0
STAT extstore_page_reclaims 0
STAT extstore_pages_free 5119
STAT extstore_pages_used 1
STAT extstore_objects_evicted 0
STAT extstore_objects_read 0
STAT extstore_objects_written 0
STAT extstore_objects_used 0
STAT extstore_bytes_evicted 0
STAT extstore_bytes_written 0
STAT extstore_bytes_read 0
STAT extstore_bytes_used 0
STAT extstore_bytes_fragmented 67108864
STAT extstore_limit_maxbytes 343597383680
```
</details>

**Comment by matthiasr** [comment]
Done in #117.
