### ISSUE TITLE
Add ability to allow or disable specific metrics

### ISSUE THREAD

**Issue by blkperl** [prometheus/memcached_exporter#118]
Would there be any interest in new configuration that allows the users to choose which metrics are sent by the exporter? I can submit a pull request.

In my use case we have thousands of pods running memcache and we have exceeded our quota for metrics so we want to restrict the metrics sent to the ones that are needed.

**Comment by SuperQ** [comment]
Typically you can handle this with `metric_relabel_configs` in Prometheus. You configure the job to `action:drop` metrics you don't use.

The collection and transport of metrics from memcached is really cheap, so there's not a lot of issues with this.

That said, if you could talk about what metrics you use/don't. It might be worth adding some flags here.

**Comment by blkperl** [comment]
> Typically you can handle this with `metric_relabel_configs` in Prometheus. You configure the job to `action:drop` metrics you don't use.

Thanks for the information! I was able to find similar configuration for our vendor's agent. It will require interacting with another internal team but that seems like the best way forward.

> The collection and transport of metrics from memcached is really cheap, so there's not a lot of issues with this.

Some of the third party vendors charge by Metric Time Series and it can add up quickly. 

> That said, if you could talk about what metrics you use/don't. It might be worth adding some flags here.

 We are still determining the exclude list be we are likely excluding `memcached_lru_crawler*`, `memcached_slab_*`, and `memcached_uptime_*`

**Comment by jdmarshall** [comment]
@blkperl Is there a reason you closed this issue?  

I'm in the same boat and I can't imagine ever needing to look at the slab stats.
