### ISSUE TITLE
how to get metrics about latency

### ISSUE THREAD

**Issue by yehaotong** [prometheus/memcached_exporter#122]
I want to get some indicators about latency. Does the exporter have any indicators about latency, or what should I do to get these indicators

**Comment by SuperQ** [comment]
Does memcached have any indicators about latency? Can you point to any docs on this?

**Comment by yehaotong** [comment]
I didn't find the index information related to latency, but I'm not sure whether there are other index information that can reflect the delay from the side. Does the exporter have an index related to the main of delay or can reflect the performance of memcached requests

**Comment by yehaotong** [comment]
> Does memcached have any indicators about latency? Can you point to any docs on this?

I didn't find the index information related to latency, but I'm not sure whether there are other index information that can reflect the delay from the side. Does the exporter have an index related to the main of delay or can reflect the performance of memcached requests

**Comment by SuperQ** [comment]
No, unless memcached exposes information via the [stats commands](https://github.com/memcached/memcached/wiki/Commands#statistics), there is no useful information the exporter can provide.
