### ISSUE TITLE
Cut new release to clear backlog of CVEs

### ISSUE THREAD

**Issue by gburton1** [prometheus/memcached_exporter#129]
Related to #112, but this is just a request to cut one quick release right away to clear a backlog of overdue CVEs (the last release was 10 months ago). The topic raised in #112 is related, but not the same; as it says, it would still be nice to systematically cut regular releases on roughly a monthly cadence.

**Comment by SuperQ** [comment]
Sorry, but image scanners don't actually prove CVEs apply to images. We regularly get reports of this kind of thing and they almost always aren't applicable.

If you want monthly images, you're welcome to build and publish images for your own internal use.
