### ISSUE TITLE
Support multi-target exporter pattern

### ISSUE THREAD

**Issue by SuperQ** [prometheus/memcached_exporter#130]
In order to support multiple / remote memcached instances (ex, SaaS managed), it would be useful to support the [multi-target exporter pattern](https://prometheus.io/docs/guides/multi-target-exporter/).

**Comment by guzelcihad** [comment]
> In order to support multiple / remote memcached instances (ex, SaaS managed), it would be useful to support the [multi-target exporter pattern](https://prometheus.io/docs/guides/multi-target-exporter/).

Do you have a plan to add this feature?

**Comment by komazarari** [comment]
Hi, how about trying https://github.com/gree/superexporter ? One of our approaches of multi-target pattern of memcached_exporter.
