### ISSUE TITLE
COPY memcached_exporter /bin/memcached_exporter

### ISSUE THREAD

**Issue by tianctrl** [prometheus/memcached_exporter#16]
I use docker hub build this Dockerfile, show me an error:

Building in Docker Cloud's infrastructure...
Cloning into '.'...

KernelVersion: 4.4.0-91-generic
Arch: amd64
BuildTime: 2017-03-28T19:26:53.326478373+00:00
ApiVersion: 1.27
Version: 17.03.1-ee-2
MinAPIVersion: 1.12
GitCommit: ad495cb
Os: linux
GoVersion: go1.7.5
Starting build of index.docker.io/tianctrl/memcached_exporter:latest...
Step 1/5 : FROM quay.io/prometheus/busybox:latest

 ---> 61c7be62c779

Step 2/5 : MAINTAINER The Prometheus Authors <prometheus-developers@googlegroups.com>

 ---> Running in a2b64f7cc8d6

 ---> 3f0be8dcb947

Removing intermediate container a2b64f7cc8d6

Step 3/5 : COPY memcached_exporter /bin/memcached_exporter

lstat memcached_exporter: no such file or directory

**Comment by grobie** [comment]
You need to run `make` first.

**Comment by tianctrl** [comment]
Oh, I see . Sorry, I thought like other exporters.   My mistake.
