### ISSUE TITLE
missing stats

### ISSUE THREAD

**Issue by jalberto** [prometheus/memcached_exporter#17]
Using:
- prom/memcached-exporter:master (also tried v.0.3.0)
- memcached:1.5.2
- k8s 1.7

After successful installation I am missing lot of memcached related stats:

```
curl memcached-exporter.ops:9150/metrics | grep memcached
# HELP memcached_up Could the memcached server be reached.
# TYPE memcached_up gauge
memcached_up 1

curl memcached-exporter.ops:9150/metrics | wc -l
126

echo -e 'stats' | nc cache-memcached.prod 11211 | grep version
STAT version 1.5.2
```

**Comment by grobie** [comment]
Anything in the logs of the memcached exporter?

**Comment by jalberto** [comment]
the usual, but no errors

**Comment by grobie** [comment]
@jalberto where you able to figure out the problem?

**Comment by pedep** [comment]
I'm currently having the same issue.
`prom/memcached-exporter:master` + `memcached:1.4.34`.

I can extract stats manually as well, but when connecting to the exporter, i only get the `memcached_up` key.

**Comment by grobie** [comment]
Unfortunately, I haven't been able to reproduce the issue so far. Can you please post the commands including all flags and other config options you're using to start memcached and memcached exporter? Are you able to reproduce the issue by starting memcached and memcached_exporter in docker containers? That should make it easier to reproduce the issue for me.

**Comment by pedep** [comment]
Sorry, i solved the issue i was having.

I am using `memcached-exporter` in a docker swarm, and i had misconfigured the host/port it was connecting to.
The `memcached_up=1` result led me to believe it successfully connected to the memcached instance, so i didn't think to look there.
After trying to reproduce in an isolated docker environment, i couldn't reproduce the issue, so i had a look, and it turned out to be the docker alias. Changing to correct hostname fixed the problem.

**Comment by pedep** [comment]
i think the `memcached=1` stat being returned when the server is down / not found is an actual bug though..

```
docker run -d -p 9150:9150 prom/memcached-exporter --memcached.address idontexist:11211

curl localhost:9150/metrics | grep memcached

# HELP memcached_up Could the memcached server be reached.
# TYPE memcached_up gauge
memcached_up 1
```

**Comment by grobie** [comment]
Indeed! I thought this might be the issue, but couldn't replicate this at
first. It turns out, we only get an error if the hostname is valid, but the
port invalid / no memcached running. If the hostname is invalid, we don't
get an error.

I'll look into that. Thanks a lot for reporting!

**Comment by pedep** [comment]
Cheers, and thanks for your quick answers :smile:
