### ISSUE TITLE
Provide ARM64 binary

### ISSUE THREAD

**Issue by kevin-zhaoshuai** [prometheus/memcached_exporter#18]
At Arm and Linaro we are working on getting Kolla-Kubernetes to deploy OpenStack on ARM64. But the deployment need to deploy memcached_exporter docker image, which the image building need haproxy_exporter binary for ARM64.

We may help with getting it built.

**Comment by grobie** [comment]
An arm64 binary is already available for the memcached exporter. For multi-arch docker support, please subscribe / comment / contribute to this promu issue https://github.com/prometheus/promu/issues/89.
