### ISSUE TITLE
Multiple instance

### ISSUE THREAD

**Issue by frenkye** [prometheus/memcached_exporter#22]
Hi,
thank you for the exporter. Do you have any plans to support multiple instance on one server? Would be nice, if we don't have to start N exporters depend on how much instance we are running. Debian support multiple instance by default.

**Comment by grobie** [comment]
So far the standpoint of the project has been to follow a strict 1:1 mapping of processes to exporters, to avoid the complexities of dealing with partial errors and process discovery. The suggested solution is to use configuration management systems to automate the management of multiple epxorters.

Similar requests are made for the HAProxy exporter. I suggest starting a thread on the prometheus developers mailing to discuss the advantages and disadvantages of the current design guide line and propose a change.

**Comment by frenkye** [comment]
I dare to disagree. It's not strict as I quote:

> In Prometheus terms, an endpoint you can scrape is called an instance, usually corresponding to a single process.  (https://prometheus.io/docs/concepts/jobs_instances/)

Sure configuration management is requirement for prometheus and I'am using it for autodiscover deployment. Maybe this would be opportunity for community fork then.

**Comment by DavidLeeUX** [comment]
> Hi,
> thank you for the exporter. Do you have any plans to support multiple instance on one server? Would be nice, if we don't have to start N exporters depend on how much instance we are running. Debian support multiple instance by default.

https://github.com/DavidLeeUX/memcached_exporter

**Comment by frenkye** [comment]
> > Hi,
> > thank you for the exporter. Do you have any plans to support multiple instance on one server? Would be nice, if we don't have to start N exporters depend on how much instance we are running. Debian support multiple instance by default.
> 
> https://github.com/DavidLeeUX/memcached_exporter

Thank you, just tested and its working!
