### ISSUE TITLE
Support for SASL authentication

### ISSUE THREAD

**Issue by benzimmer** [prometheus/memcached_exporter#25]
Memcached supports authentication through SASL (https://github.com/memcached/memcached/wiki/SASLAuthProtocol).

It would be nice if the exporter could also fetch data from protected memcached instances.

If you have any suggestions for a workaround, I'd also be highly interested 😁

**Comment by grobie** [comment]
@benzimmer The exporter is meant to be deployed next to the memcached instance. Isn't it possible to allow local access without authentication?

**Comment by benzimmer** [comment]
@grobie As far as I understood from the docs it's all-in or nothing but would be very happy if someone has a different opinion and points me into the right direction 😃

**Comment by denisgolius** [comment]
> @benzimmer The exporter is meant to be deployed next to the memcached instance. Isn't it possible to allow local access without authentication?

Yes, it's not possible, because for compose-cluster, k8s and other orchestration tools this resolved by RBAC/service/internal networks/firewalls, but if memcached run in docker+sasl without them - you can't connect anyway. Use it without SASL is the simplest solution, but not useful for all.
