### ISSUE TITLE
conn_yields and listen_disabled_num

### ISSUE THREAD

**Issue by elukey** [prometheus/memcached_exporter#33]
Hi!

I am wondering if it would be worth to add conn_yields and listen_disabled_num to the exporter. They seems to be very useful metrics that should be reported. In case the answer is yes I can help and send a patch to review :)

Luca

**Comment by grobie** [comment]
Hey @elukey. The `conn_yields` metric looks definitely interesting. I couldn't immediately find any documentation on `listen_conn_disabled`, can you provide a link?

I'd be happy to accept PRs to add these metrics. Please keep in mind to handle the absence gracefully in case metrics are not available in all memcached versions. Have a look at the other metrics and follow existing naming patterns, this page might also be interesting https://prometheus.io/docs/practices/naming/.

**Comment by elukey** [comment]
Thanks for the answer! I realized that I mistyped the metric name, that is `listen_disabled_num`:

https://github.com/memcached/memcached/wiki/ServerMaint

```
listen_disabled_num
An obscure named statistic counting the number of times memcached has hit its connection limit. When memcached hits the max connections setting, it disables its listener and new connections will wait in a queue. When someone disconnects, memcached wakes up the listener and starts accepting again.
```

**Comment by elukey** [comment]
@grobie Added a pull request for the conn_yield metric, let me know if it is acceptable or not. I quickly tested it and it seems working as expected.

**Comment by grobie** [comment]
@elukey What about `listen_disabled_num`, wanna send a PR for that as well?

**Comment by elukey** [comment]
Just opened a pull request :)

**Comment by elukey** [comment]
Thanks a lot @grobie! Last favor that I'd ask is, whenever possible, to release a new version so it will be easier to package it (in my case, Debian). Otherwise I'll simply package up to my commit and that's it :)

**Comment by grobie** [comment]
Of course. Will do that tonight.

**Comment by grobie** [comment]
https://github.com/prometheus/memcached_exporter/releases/tag/v0.5.0
