### ISSUE TITLE
Support Unix  protocol

### ISSUE THREAD

**Issue by ciceroverneck** [prometheus/memcached_exporter#34]
Start memcached with unix params
`
mecached -s /var/run/memcached.sock  -a 755
`

Start exporter (but not work). 
`
memcached_exporter --memcached.address /var/run/memcached.sock 
`

**Comment by cemir** [comment]
feature also needed here

if it helps, `nc` is able to communicate through unix socket :

`echo 'stats' | nc -U /path/to/memcache.sock`

**Comment by cemir** [comment]
actually it works but with rights set to 775 if using a different user/same group

**Comment by akshatgit** [comment]
Is this feature being worked upon? If not, I'd like to contribute.

**Comment by ciceroverneck** [comment]
It already works in new versions.

```
/bin/memcached_exporter --memcached.address /var/run/sockets/memcached.sock
```
