### ISSUE TITLE
Keep memcached connection open

### ISSUE THREAD

**Issue by grobie** [prometheus/memcached_exporter#37]
An overloaded memcached server will refuse to accept new connections, see https://github.com/memcached/memcached/wiki/ServerMaint#important-stats. As it's important to export metrics about that state as added in #36, we should consider to keep the connection from the exporter open all time, once it has been established. This might include sending pings to prevent it from being closed.

**Comment by brian-brazil** [comment]
As concurrent scrapes are a thing, that probably means keeping a connection pool.

**Comment by tr2vil** [comment]
this means...

**Comment by tr2vil** [comment]
Does this mean that memcached_exporter always keeps the connection to the memcached daemon?

**Comment by SuperQ** [comment]
IMO, failing to scrape because new connections can't be made is a feature. This is a valid test case that the exporter should provide.

**Comment by SuperQ** [comment]
Similar to the way we always open new connections in the mysqld_exporter, as a feature to validate that new connections are possible (`memcached_up` metric). This can be closed.
