### ISSUE TITLE
Don't use NaNs as error values

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/memcached_exporter#38]
NaNs should only be used in cases where they make mathematical sense. If there's an error you should generally fail the scrape or set up to 0.

See https://stackoverflow.com/questions/53430836/prometheus-sum-one-nan-value-result-into-nan-how-to-avoid-it/

**Comment by f110** [comment]
@SuperQ 

Are you working in progress this?
If not, I will create a pull request later.

**Comment by SuperQ** [comment]
I am not working on it, a PR would be great.
