### ISSUE TITLE
[Question] Use of grobie/gomemcache instead of bradfitz/gomemcache ?

### ISSUE THREAD

**Issue by erikwebb** [prometheus/memcached_exporter#45]
This is just a simple question to understand the usage of a forked repo, rather than the original. Are there any specific differences that are required for this exporter to work? That would be good to understand in the documentation.

I ran the latest `master` branch using the `bradfitz/gomemcache` module and tests do fail -
```
$ perl -pi -e 's|github.com/grobie/gomemcache/memcache|github.com/bradfitz/gomemcache/memcache|' main.go
$ make
>> checking code style
>> running staticcheck
chmod +x /usr/local/google/home/erikwebb/go/bin/staticcheck
GO111MODULE=on go list -e -compiled -test=true -export=false -deps=true -find=false -tags= -- ./... > /dev/null
go: finding github.com/bradfitz/gomemcache/memcache latest
go: finding github.com/bradfitz/gomemcache latest
GO111MODULE=on /usr/local/google/home/erikwebb/go/bin/staticcheck -ignore "" ./...
main.go:352:12: cannot initialize 2 variables with 1 values (compile)
main.go:352:12: cannot initialize 2 variables with 1 values (compile)
main.go:352:12: cannot initialize 2 variables with 1 values (compile)
Makefile.common:142: recipe for target 'common-staticcheck' failed
make: *** [common-staticcheck] Error 1
```

**Comment by grobie** [comment]
https://github.com/bradfitz/gomemcache/compare/master...grobie:master

1. Support for memcached stats call (which is the main feature of this exporter)
2. Fix missing handling of connection errors

**Comment by erikwebb** [comment]
Thanks! I'm just seeing the PRs for those features. I didn't realize the original repo had become so stagnant.
