### ISSUE TITLE
"memcached_up" add memcached address variables

### ISSUE THREAD

**Issue by lyt8384** [prometheus/memcached_exporter#48]
now “memcached_up” variables just has exporter serves address, when multiple exporters in one serves, it`s very hard to distinguish which one is i need. Would be nice, if can add memcached address value in “memcached_up” variables.
like [redis_exporter](https://github.com/oliver006/redis_exporter)
thx!

**Comment by DavidLeeUX** [comment]
https://github.com/DavidLeeUX/memcached_exporter

**Comment by lyt8384** [comment]
> https://github.com/DavidLeeUX/memcached_exporter

suggest to create a release version for download.

**Comment by DavidLeeUX** [comment]
> > https://github.com/DavidLeeUX/memcached_exporter
> 
> suggest to create a release version for download.

https://github.com/DavidLeeUX/memcached_exporter/releases/tag/0.6.0
