### ISSUE TITLE
Release 0.1.0 ?

### ISSUE THREAD

**Issue by sdurrheimer** [prometheus/memcached_exporter#6]
@grobie What's your plan for this ? IIRC you wanted to do the slab support before that, but maybe can we cut a 0.1.0 and keep the slab metrics for the 0.2.0.

**Comment by ipstatic** [comment]
Now that slab metrics have been ported, can either a 0.1.0 or 0.2.0 release be cut?

**Comment by grobie** [comment]
I'd even say a 0.3.0 release. 0.1.0 was the original memcache_exporter (without `e`). `0.2.0` was never officially released but is in use by at least two companies.

I was about to do that and got asked to sneak in another metric to exporter the maximum possible amount of connections. I'm working on this right now, but even in case I don't make it I'll cut a proper release this weekend.

**Comment by grobie** [comment]
Fixed with the release of [v0.3.0](https://github.com/prometheus/memcached_exporter/releases/tag/v0.3.0).
