### ISSUE TITLE
Switch logging to go-kit

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/memcached_exporter#72]
About two years ago we decided to move from logrus to go-kit for logging, this is one of the repos that still needs switching. https://github.com/prometheus/snmp_exporter/pull/447 is an example PR.

**Comment by bharaththiruveedula** [comment]
@brian-brazil Can I start with this?

**Comment by brian-brazil** [comment]
Go ahead

**Comment by bharaththiruveedula** [comment]
Thanks .... I am working on it

**Comment by grobie** [comment]
Done in #73.
