### ISSUE TITLE
Failed to collect stats from memcached: dial tcp 127.0.0.1:11211

### ISSUE THREAD

**Issue by ivanzor** [prometheus/memcached_exporter#79]
My error:  **msg="Failed to collect stats from memcached: dial tcp 127.0.0.1:11211: connect: connection refused" source="main.go:517"**

I run container like this: 
`docker run -d -p 9150:9150 prom/memcached-exporter --memcached.address 127.0.0.1:11211`

My memcached listen localhost:11211

```
netstat -tunlp | grep memcached                                                                                                                                               
tcp        0      0 127.0.0.1:11211         0.0.0.0:*               LISTEN      8310/memcached
```

I can connect to via cli:
` telnet 127.0.0.1 11211                                                                                                                                                        root@www
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
stats
STAT pid 8310
STAT uptime 626626
`
What am I doing wrong?

**Comment by grobie** [comment]
I hope you were able to solve the connection issue. Please ask in the Prometheus users mailing list for help otherwise.

**Comment by shenwxopen** [comment]
my error: msg"level=error msg="Failed to connect to memcached: address tcp/11211\": unknown port" source="main.go:509""
I used version v0.6.0
I  run container like this:
```
docker run -d -p 9150:9150 prom/memcached-exporter --memcached.address=ip:11211
```

**Comment by ezavgorodniy** [comment]
@ivanzor instead of 127.0.0.1 you need to put your actual IP address
