### ISSUE TITLE
Documentation inconsistency

### ISSUE THREAD

**Issue by deanwilson** [prometheus/memcached_exporter#84]
Hello.

In the READMEs in the quay and docker registries the default port is listed as 9106, but in GitHub, and when running, it's 9150.

"By default the memcache_exporter serves on port 0.0.0.0:9106 at /metrics"
https://quay.io/repository/prometheus/memcached-exporter?tab=info
https://hub.docker.com/r/prom/memcached-exporter

"By default the memcache_exporter serves on port 0.0.0.0:9150 at /metrics:"
https://github.com/prometheus/memcached_exporter

Port 9150 is used throughout the code base and so should be the correct one. I can't find 9106 in the repo otherwise I would have raised a PR to fix the docs.

Thank you for your time.

**Comment by grobie** [comment]
Thanks a lot @deanwilson! The default port was changed 4 years ago https://github.com/prometheus/memcached_exporter/commit/68d1601a5166aa1225f13533081861c5c534a289 TIL that docker/quay readme's are not kept in sync with the source readme. I updated both manually.
